feat: comment table, save comment 추가
SD-woomool/SpringServer pull request #26
Opened 2022-02-07 17:14 UTC by ykh8383633

2022-02-08 15:14 UTC, ykh8383633 commented on src/main/java/app/joycourse/www/prod/service/CourseService.java
> +                pageLength,
전에 했던건데 코드 못생겨서 바꾼거 및에 함수도

2022-02-09 06:45 UTC, seokh1213 requested changes

2022-02-09 06:45 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/controller/CommentController.java
> +@Controller
RestController 아니여도 잘작동해?

2022-02-09 06:45 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/domain/User.java
> +    private List<Comment> comments;
course, comments 둘다  User에 없어도되지않어??
조회할때 userId 를 이용해서 course, coments 가져오면되지않을가?

User 조회할때 Lazy여도 사용할일이 있을까 고민이네 ㅋㅋ

2022-02-09 06:45 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/dto/CommentSaveRequestBodyDto.java
> +    private Comment comment;
Entity 바로넣어도될려나?? 
CommentSaveRequestBodyDto 이것처럼 Request용 dto 만드는게 낫지않을가??

2022-02-09 15:59 UTC, seokh1213 approved these changes
good

2022-02-09 17:05 UTC, merged