Feature/cache auth
SD-woomool/SpringServer pull request #46
Opened 2022-04-07 18:23 UTC by ykh8383633

2022-04-08 16:37 UTC, seokh1213 requested changes
확인해주셈!

2022-04-08 16:37 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/service/CourseService.java
> +    @CacheEvict(value = "user", key = "#user.nickname")
value를 `user/my-course` 이런걸로 바꾸는거어떰? 다른 유저전용 캐시랑 겹칠듯? 
key도 이왕이면 `nickname=#user.nickname` 이렇게 명시적으로

2022-04-08 16:37 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/service/UserService.java
> +    @CacheEvict(value = "user", key = "#user.nickname") // -> 테스트 사용자 없어지면 key = "#user.uid"로 바꾸자
여기도 같이 바꿔주셈

2022-04-08 16:37 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/service/UserService.java
> +    @Cacheable(value = "user", key = "#uid", cacheManager = "cacheManger")
이런것도 value user해도되고 key를 `userUid=#uid` 이런느낌으로 키바꿔주셈

2022-04-08 16:37 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/service/UserService.java
> +    @Cacheable(value = "user", key = "#nickname", cacheManager = "cacheManager") // -> 테스트 사용자 없어지면 지우자
이것도 key `nickname=#nickname` 이런걸로 바꿔줘

2022-04-08 16:37 UTC, seokh1213 commented on src/main/java/app/joycourse/www/prod/service/auth/AuthService.java
> +    public Optional<Auth> getAuthByUid(String uid) {
이거는 캐싱안한이유가 MSA환경에서 나눠질까봐?

2022-04-08 16:37 UTC, seokh1213 commented on 
> +  feature/CRUD-comments[m
이거파일은 뭐야??

2022-04-08 16:41 UTC, huiseung commented on src/main/java/app/joycourse/www/prod/service/CourseService.java
> +    @CacheEvict(value = "user", key = "#user.nickname")
good idea

2022-07-05 00:04 UTC, seokh1213 approved these changes

2022-07-05 06:59 UTC, merged